language: node_js
node_js: stable
sudo: required

# 构建的分支
branches:
  only:
    - master

before_install:
  # Repo for Yarn
  # RF：https://yarnpkg.com/lang/en/docs/install-ci/
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

  # 安装对应版本的 theme next
  - git submodule update --init

install:
  - yarn install

script:
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: gh-pages
  keep-history: false
  on:
    branch: master

cache:
  yarn: true
